name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - test # 添加 test 分支
    paths:
      - 'src/**'
      - '.github/workflows/docker-build.yml'
      - 'requirements.txt'
      - 'dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 授予写入 ghcr.io 的权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile 所在的目录
          push: true
          file: ./dockerfile
          tags: |
            ghcr.io/${{ github.actor }}/hentai-assistant:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && format('ghcr.io/{0}/hentai-assistant:latest', github.actor) || '' }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: BUILDKIT_INLINE_CACHE=1